### ISSUE TITLE
Endpoint::Transfer in READ mode expects uint32_t as first parameter

### ISSUE THREAD

**Issue by geuis** [schakko/node-usb#10]
System: Mac 10.6.8
Node: 0.6.14
libusb: git://git.libusb.org/libusb.git via http://libusb.org/wiki/libusb-1.0#Documentation

Had to "brew install pkg-config" to for libusb-1.0 to be found by node-usb

After building node-usb, node-usb-test.js fails with:

"TypeError: Endpoint::Transfer in READ mode expects uint32_t as first parameter. If you want to write something, you must provide a Buffer instance as first parameter"

Full build log follows:

geuiss-Mac-Pro:nodeusb geuis$ make
node-waf -v configure clean build; node tests/node-usb-test.js
Checking for program g++ or c++          : /Developer/usr/bin/g++ 
Checking for program cpp                 : /Developer/usr/bin/cpp 
Checking for program ar                  : /Developer/usr/bin/ar 
Checking for program ranlib              : /Developer/usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /Developer/usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.14 
Checking for libusb-1.0                  : 21:29:22 runner pkg-config --errors-to-stdout --print-errors --cflags --libs libusb-1.0 
yes 
'configure' finished successfully (0.066s)
'clean' finished successfully (0.005s)
Waf: Entering directory `/usr/local/apps/nodeusb/build'
[1/6] cxx: src/node_usb.cc -> build/Release/src/node_usb_1.o
21:29:22 runner system command -> ['/Developer/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.14/include/node', '-DNODE_USB_REVISION="8706aaa22bbfcd50b9c5b99bdd3a0c6add376dc4"', '../src/node_usb.cc', '-c', '-o', 'Release/src/node_usb_1.o']
[2/6] cxx: src/usb.cc -> build/Release/src/usb_1.o
[3/6] cxx: src/device.cc -> build/Release/src/device_1.o
21:29:22 runner system command -> ['/Developer/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.14/include/node', '-DNODE_USB_REVISION="8706aaa22bbfcd50b9c5b99bdd3a0c6add376dc4"', '../src/usb.cc', '-c', '-o', 'Release/src/usb_1.o']
21:29:22 runner system command -> ['/Developer/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.14/include/node', '-DNODE_USB_REVISION="8706aaa22bbfcd50b9c5b99bdd3a0c6add376dc4"', '../src/device.cc', '-c', '-o', 'Release/src/device_1.o']
[4/6] cxx: src/interface.cc -> build/Release/src/interface_1.o
[5/6] cxx: src/endpoint.cc -> build/Release/src/endpoint_1.o
21:29:22 runner system command -> ['/Developer/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.14/include/node', '-DNODE_USB_REVISION="8706aaa22bbfcd50b9c5b99bdd3a0c6add376dc4"', '../src/interface.cc', '-c', '-o', 'Release/src/interface_1.o']
21:29:22 runner system command -> ['/Developer/usr/bin/g++', '-g', '-Wall', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=1', '-IRelease', '-I..', '-I/usr/local/include/libusb-1.0', '-I/usr/local/Cellar/node/0.6.14/include/node', '-DNODE_USB_REVISION="8706aaa22bbfcd50b9c5b99bdd3a0c6add376dc4"', '../src/endpoint.cc', '-c', '-o', 'Release/src/endpoint_1.o']
../src/device.cc: In static member function ‘static void NodeUsb::Device::EIO_ControlTransfer(uv_work_t*)’:
../src/device.cc:396: warning: comparison is always false due to limited range of data type
[6/6] cxx_link: build/Release/src/node_usb_1.o build/Release/src/usb_1.o build/Release/src/device_1.o build/Release/src/interface_1.o build/Release/src/endpoint_1.o -> build/Release/usb_bindings.node
21:29:22 runner system command -> ['/Developer/usr/bin/g++', 'Release/src/node_usb_1.o', 'Release/src/usb_1.o', 'Release/src/device_1.o', 'Release/src/interface_1.o', 'Release/src/endpoint_1.o', '-o', '/usr/local/apps/nodeusb/build/Release/usb_bindings.node', '-bundle', '-undefined', 'dynamic_lookup', '-L/usr/local/lib', '-L/usr/local/Cellar/node/0.6.14/lib', '-lusb-1.0']
Waf: Leaving directory`/usr/local/apps/nodeusb/build'
'build' finished successfully (0.796s)
Failed to claim endpoint; error: -99
Failed to claim endpoint; error: -99
Failed to claim endpoint; error: -99
Failed to claim endpoint; error: -99
Failed to claim endpoint; error: -99

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Endpoint::Transfer in READ mode expects uint32_t as first parameter. If you want to write something, you must provide a Buffer instance as first parameter
    at Object.<anonymous> (/usr/local/apps/nodeusb/tests/node-usb-test.js:88:24)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
make: **\* [make] Error 1

**Comment by schakko** [comment]
You can ignore this error.

I fixed it in 61986afa8d and added documentation in f0747e6b9a
