### ISSUE TITLE
usb_bindings.node: undefined symbol: ev_rt_now

### ISSUE THREAD

**Issue by schakko** [schakko/node-usb#4]
I changed the dependencies with the commit https://github.com/schakko/node-usb/commit/435e8b97ded4343348c6f9cdc47230a377e9b65d the dependencies from libev to libuv.

After compiling the module under v0.5.9 I get the error "usb_bindings.node: undefined symbol: ev_rt_now".
v0.6.7 and pre-v0.7.0 returns "unable to load shared library node usb_bindings.node" - with gdb (http://stackoverflow.com/questions/8701240/unable-to-load-nowjs-now-js) I get the same error "undefined symbol: ev_rt_now".

nm usb_bindings | grep "ev" returns

0001019c t ev_now
00013fd5 t ev_now
         U ev_ref
         U ev_rt_now
         U ev_run
000073c1 t ev_unloop
00007889 t ev_unloop

Environment: 2.6.35-31-generic #63-Ubuntu SMP Mon Nov 28 19:23:11 UTC 2011 i686 GNU/Linux

**Comment by schakko** [comment]
Fixed.

**Comment by erenon** [comment]
@schakko: I have the same problem, how did you fix this?

**Comment by schakko** [comment]
After I had changed the node_usb bindings from libev to libuv and doing some other changes (7b78e10db3f26a0e2886beaeb92e1d7a9ae0472f), the error went away. Not sure, what it was exactly.
