### ISSUE TITLE
libusb-1.0 not found

### ISSUE THREAD

**Issue by geuis** [schakko/node-usb#9]
On Mac 10.6.8, node 0.6.14.

Given that Homebrew installation of libusb is not recommended, I installed the latest version of libusb that is being actively developed from here: git://git.libusb.org/libusb.git as is recommended by http://libusb.org/wiki/libusb-1.0#Documentation.

Installation appears successful of libusb. Running make in node-usb results in:

node-waf -v configure clean build; node tests/node-usb-test.js
Checking for program g++ or c++          : /Developer/usr/bin/g++ 
Checking for program cpp                 : /Developer/usr/bin/cpp 
Checking for program ar                  : /Developer/usr/bin/ar 
Checking for program ranlib              : /Developer/usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /Developer/usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.11 
Checking for libusb-1.0                  : 00:36:10 runner pkg-config --errors-to-stdout --print-errors --cflags --libs libusb-1.0 
not found 
/usr/local/apps/nodeusb/wscript:21: error: the configuration failed (see '/usr/local/apps/nodeusb/build/config.log')

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module './usb_bindings'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/apps/nodeusb/usb.js:4:15)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
make: **\* [make] Error 1

The error is here, "Checking for libusb-1.0 : 00:36:10 runner pkg-config --errors-to-stdout --print-errors --cflags --libs libusb-1.0"

libusb-1.0 is not found.

How do I correct this?

**Comment by schakko** [comment]
Does `pkg-config --libs libusb` or `pkg-config --libs usb` work?

**Comment by geuis** [comment]
Neither of those commands runs when executed in the node-usb directory. I had to brew install pkg-config just to try them.

The messages I get for each command are, in turn:

geuiss-Mac-Pro:nodeusb geuis$ pkg-config --libs libusb
Package libusb was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb' found

geuiss-Mac-Pro:nodeusb geuis$ pkg-config --libs usb
Package usb was not found in the pkg-config search path.
Perhaps you should add the directory containing `usb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'usb' found

**Comment by schakko** [comment]
Ok, does `pkg-config --libs libusb-1.0` now work? The error above occured 'cause you did not have installed pkg-config...

**Comment by geuis** [comment]
Since the time earlier that I filed the issue, I reinstalled libusb via homebrew, hence the path in this message:

-L/usr/local/Cellar/libusb/1.0.8/lib -lusb-1.0

**Comment by schakko** [comment]
Aww... that seems to be correct.

**Comment by geuis** [comment]
That seems to have fixed this particular issue. It might be useful to add a check for pkg-config to the build process as a requirement.

**Comment by schakko** [comment]
wscript searches for pkg-config (f0747e6)
